name: Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and run dev container task
      uses: devcontainers/ci@v0.3
      with:
        runCmd: jupyter execute analyse_qotw/Analysis.ipynb
        push: never
    - uses: azure/login@v2
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v2
      with:
        inlineScript: |
            az storage blob upload-batch --account-name assetstomsloftnetprodst --overwrite true --auth-mode key -d '$web' -s output
